### PR TITLE
Add Docker environment & web demo

### PR DESCRIPTION
**Pull request by ericguizzo**
Hey @f90!

I really appreciate your wave-u-net implementation! 

This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can try out your model! View it here: https://replicate.ai/f90/wave-u-net-pytorch

[Claim your page here](https://replicate.ai/f90/wave-u-net-pytorch?published=1) so you can edit it, and we'll feature it on our website and tweet about it too.

In case you're wondering who I am, I'm from [Replicate](https://replicate.ai/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Comment by f90** [comment]
Hey, thanks for the pull request. Looks exciting! I will take a look at it on the weekend, is there anything on my end I need to do code-wise to merge this successfully or do I just need to review?

**Comment by f90** [comment]
Looking good, I suppose if I change/improve the model in the master branch it will automatically be improving on your website as well, or how does that work? @ericguizzo

**Comment by f90** [comment]
Btw I claimed the model on your website you were linking to, seems to work already :) Nice job, hope you'll be very successful :+1:

**Comment by f90** [comment]
Pinging @ericguizzo , I can just merge this now and everything works right?

**Comment by ericguizzo** [comment]
Hello f90, sorry for the late response! Thank you very much for merging the pull request and for claiming the model! 
Everything seems to work fine :)

**Pull request merged**
